export const SLIDES = {
  INIT: "INIT_SLIDES",
  CLEAR_ALL: "CLEAR_SLIDES"
};

export const PRESENTATION = {
  ADD_SLIDES: "ADD_SLIDES",
  SELECT_SLIDE: "SELECT_SLIDES"
};

export const SHEETS = {
  INIT: "INIT_SHEETS",
  CLEAR_ALL: "CLEAR_SHEETS"
}

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
